### ISSUE TITLE
Add an annotation to ignore

### ISSUE THREAD

**Issue by tebaly** [jawira/doctrine-diagram-bundle#12]
The Symfony messenger uses the doctrine entity to store the data in the database. This table is useless in a diagram.

> messenger_messages

> doctrine_migration_versions

**Comment by jawira** [comment]
Hello, I understand what you are asking but it would be very difficult to implement it:

- first because "doctrine-diagram-bundle" uses a library called [db-draw](https://github.com/jawira/db-draw/) which does not relies on entities to generate the diagrams. db-draw uses de DBAL layer of doctrine, not the ORM layer.
- nevertheless I have planned to [add support to Entities in db-draw](https://github.com/jawira/db-draw/issues/6) but currently I don't have any time so I suppose I will work on this in 2024.

Finally keep in mind that I want to keep doctrine-diagram-bundle with fewer features as possible, I only want to generate db diagrams to keep track of DB evolution, and I usually put that diagrams in the readme file of my projects. 

I will close this issue, but feel free to re-open it or create a new one.

**Comment by jawira** [comment]
FYI now you can ignore tables using `--exclude` option in command line, and `exclude:` key in doctrine_diagram.yaml
