### ISSUE TITLE
Run bundle as CLI tool without integrate with own project 

### ISSUE THREAD

**Issue by mesilov** [jawira/doctrine-diagram-bundle#13]
I use symfony components (doctrine, serializer, etc) without core, can I run this package as separated CLI tool like  open-api generator?

--targetFolder="/src/domain/models/" --resultFolder="/documentation/database/"

**Comment by jawira** [comment]
Hi, you can give a try to <https://github.com/jawira/mysql-draw>, it works only for mysql db.
Otherwise, doctrine-diagram-bundle and mysql-draw both relies on db-draw <https://github.com/jawira/db-draw> which is the library that does all the work.
I'm closing the issue but feel free to re-open this issue or create a new one.
